# Generated by Django 4.1.7 on 2023-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_genre_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='content',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
